//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Project_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Bid { get; set; }
        public string Btitle { get; set; }
        public string BCategory { get; set; }
        public string BDesc { get; set; }
        public string BUrl { get; set; }
    }
}
